version: '3.9'

services:
  dfbackendtombola:
    container_name: df-backend-tombola
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    extends:
      file: backend-compose.yml
      service: development
    ports:
      - $PORT:$PORT
    expose:
      - $PORT
  